---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/scores":
    post:
      summary: Creates scores
      tags:
      - Scores
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: scores created
        '400':
          description: bad request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  username:
                    type: string
                    format: email
                  seconds:
                    type: integer
                  published_at:
                    type: string
                    format: date-time
              required:
              - username
              - seconds
              - published_at
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.statswithfriends.com
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
